### ISSUE TITLE
Call to undefined function llorix_one_companion_sevices_get_default_content() in v1.1.2

### ISSUE THREAD

**Issue by jasonl1** [Codeinwp/llorix-one-companion#33]
When i updated my site I got a fatal error
PHP Fatal error:  Call to undefined function llorix_one_companion_sevices_get_default_content() in /var/www/vhosts/.../httpdocs/wp-content/plugins/llorix-one-companion/sections/our-services-section.php on line 9

When I compared the latest version to a previous on the llorix_one_companion_sections had incorrect links to the companion sections - correction in bold below in llorix-one-companion.php. Was this a botched autoupdate on WP?

function llorix_one_companion_sections() {
	return array(
		'sections/llorix_one_lite_logos_section',
		**'llorix_one_lite_our_services_section**', //'our-services-section',
		'sections/llorix_one_lite_our_story_section',
		'l**lorix_one_lite_our_team_section**', //'our-team-section',
		'**llorix_one_lite_happy_customers_section**', //'happy-customers-section',
		'sections/llorix_one_lite_content_section',
		'sections/llorix_one_lite_ribbon_section',
		'sections/llorix_one_lite_latest_news_section',
		'sections/llorix_one_lite_contact_info_section',
		'sections/llorix_one_lite_map_section'
	);
}

**Comment by rodica-andronache** [comment]
Hi @jasonl1 ,

Thank you for contacting us. I'm really sorry to hear that you have this issue.
Can you please let me know if you have the latest version of Llorix One Lite?

Regards,
Rodica

**Comment by jasonl1** [comment]
Yes, we just updated on Apr 19

**Comment by rodica-andronache** [comment]
Hi @jasonl1 ,

We just released an update for the plugin that should fix this error. Are you still able to update the plugin? 
Let me know.

Rodica
