### ISSUE TITLE
Our team, Our Services and Testimonials not displaying

### ISSUE THREAD

**Issue by CloudSpanse** [Codeinwp/llorix-one-companion#40]
The options to customize the Our Team, Our Services and Testimonials are there, but they do not appear on the actual website.

**Comment by rodica-andronache** [comment]
Hi @CloudSpanse ,

Thank you for contacting us! 
Can you please give me your site URL so I can see the issue? Also, are you using the latest version of both the theme Llorix One Lite and the plugin Llorix One Companion?

Regards,
Rodica

**Comment by srushik** [comment]
I am having the exact same issue.  The sections mentioned do not appear on the website.  Are there any updates to this issue, or work-arounds that can be implemented to display those sections?

**Comment by rodica-andronache** [comment]
Hi @srushik ,

Do you have the latest version of both the theme Llorix One Lite and the plugin Llorix One Companion?

Regards,
Rodica

**Comment by srushik** [comment]
I have the latest llorix one companion, but I do not have the Llorix One Lite.  I never had the Lite plugin installed.  The sections just stopped working with a recent update.

**Comment by rodica-andronache** [comment]
Hi @srushik ,

Clarina is a child theme of the Llorix One Lite theme, which means you are using that theme too, as a parent theme. With the latest updates of the parent theme, and the companion plugin, this problem appeared in Clarina, and beeing a child theme ( where users usually change the files ) we can't update it to fix the problem.
But there is an easy solution for that, you just need to follow this doc here  http://docs.themeisle.com/article/635-how-to-display-sections-from-llorix-one-companion-in-clarina

Let me know if you manage to do that.

Regards,
Rodica

**Comment by srushik** [comment]
That is a great explanation and thank you for the fix.  Unfortunately, when I replace that section of code, the home page now displays this gethub content.  here is a url to see what I'm describing: http://pitchcounterpro.com

**Comment by srushik** [comment]
That is a great explanation and thank you for the url.  

Unfortunately, when I replace that section of code, the home page now displays this gethub content.  

It seems, that for some reason replacing:
    >>'llorix_one_lite_our_services_section',
with
    >> 'our-services-section', 
causes the web page to display the gethub web content. 

I don't understand why it would link to the gethub content, that is bizarre...
Is there something else that I need to modify to over come that?

**Comment by rodica-andronache** [comment]
Hi @srushik ,

Did you replace the content as explained in the doc? Is there any chance that you missed part of the code, a quote something? Can you please give me your site URL so I can see the issue?

Thank you,
Rodica

**Comment by srushik** [comment]
yea, the instructions are pretty easy to follow.  Here is a URL.

**Comment by rodica-andronache** [comment]
Hi @srushik ,

Based on how the site looks, it's clearly that you somehow copied something different than what it was mentioned in the doc I gave you. You somehow added the source code from the github page there.
Can you maybe share the whole content of your child themes files so I can tel where the problem is?

Thank you,
Rodica

**Comment by srushik** [comment]
okay, so you saying that made the think about what other edits I added to try to fix this.  At one point, I edited the file: llorix-one-companion/sections/our-services-section.php
I reverted back to the previous version of this file, and that restored the functionality correctly.  So, obviously, I just goofed that up somehow.

Looks like it is working correctly now.  All thank you so much for all your help.

**Comment by rodica-andronache** [comment]
Hi @srushik ,

I'm glad to hear I was able to help you and everything is ok now. If you are happy with the theme or our support you can always leave us a review here https://wordpress.org/support/plugin/llorix-one-companion/reviews/#new-post
We would really appreciate it.

Regards,
Rodica

**Comment by srushik** [comment]
Thanks.  I posted a review.  5-stars!!

**Comment by rodica-andronache** [comment]
Thanks. Really appreciate this :D
