### ISSUE TITLE
Translations for sections repeater

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-companion#7]

**Comment by rodica-andronache** [comment]
@cristian-ungureanu how long do you think this will take? can you please add an estimate?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu how is this going? I don't think you created a pull request with this

**Comment by rodica-andronache** [comment]
can you please give an update here?

**Comment by cristian-ungureanu** [comment]
I don't know ... I really hate translation plugins. I'll have to do it again, I don't even remember what I did in april.
